const language = {
  en: {
    SEARCH: "Search",
    GPT_SEARCH_PLACEHOLDER: "What would you like to watch today?",
    GPT_SEARCH: "GPT Search",
    SIGN_OUT: "Sign out",
    SIGN_IN: "Sign In",
    SIGN_UP: "Sign Up",
    FULL_NAME: "Full Name",
    EMAIL: "Email",
    PASSWORD: "Password",
    NEW_USER_PROMPT: "New to Netflix? Sign Up Now",
    OLD_USER_PROMPT: "Already a User? Sign In Now",
    POPULAR_MOVIES: "POPULAR",
    NOW_PLAYING: "NOW PLAYING",
    TOP_RATED: "TOP RATED",
    UPCOMING: "UPCOMING",
    HOME_PAGE:"Home Page"
  },
  tibetan: {
    SEARCH: "བཤེར་འཚོལ",
    GPT_SEARCH_PLACEHOLDER: "དེ་རིང་ཁྱེད་རང་ག་རེ་ལྟ་འདོད་ཡོད་དམ།",
    GPT_SEARCH: "GPT འཚོལ་ཞིབ།",
    SIGN_OUT: "ཐོ་འགོད།",
    SIGN_IN: "ཐོ་འགོད།",
    SIGN_UP: "ཐོ་འགོད།",
    FULL_NAME: "མིང་ཆ་ཚང་།",
    EMAIL: "གློག་འཕྲིན།",
    PASSWORD: "གསང་གྲངས",
    NEW_USER_PROMPT: "ནེཊ་ཕི་ལིག་སི་ལ་གསར་པ་རེད་དམ། ད་ལྟ་ཐོ་འགོད་བྱོས།",
    OLD_USER_PROMPT: "ད་ལྟ་སྤྱོད་མཁན་ཞིག་ཡིན་ནམ། ད་ལྟ་ཐོ་འགོད་བྱོས།",
    POPULAR_MOVIES: "དར་སྲོལ་ཆེན་པོ",
    NOW_PLAYING: "ད་ལྟ་རྩེད་བཞིན་ཡོད།",
    TOP_RATED: "ཆེས་མཐོའི་ཚད་གཞི།",
    UPCOMING: "འབྱུང་འགྱུར།",
    HOME_PAGE:"གཙོ་ངོས།"
  },
  spanish: {
    SEARCH: "Buscar",
    GPT_SEARCH_PLACEHOLDER: "¿Qué te gustaría ver hoy?",
    GPT_SEARCH: "Búsqueda GPT",
    SIGN_OUT: "DESCONECTAR",
    SIGN_IN: "Iniciar sesión",
    SIGN_UP: "Inscribirse",
    FULL_NAME: "Nombre completo",
    EMAIL: "Correo electrónico",
    PASSWORD: "contraseña",
    NEW_USER_PROMPT: "¿Nuevo en Netflix? Regístrate ahora.",
    OLD_USER_PROMPT: "¿Ya eres usuario? Inicia sesión ahora.",
    POPULAR_MOVIES: "POPULAR",
    NOW_PLAYING: "Reproduciendo ahora",
    TOP_RATED: "MEJOR CALIFICADA",
    UPCOMING: "Próximamente",
    HOME_PAGE:"Página de inicio"
  },
  hindi: {
    SEARCH: "खोज",
    GPT_SEARCH_PLACEHOLDER: "आज आप क्या देखना चाहेंगे?",
    GPT_SEARCH: "GPT खोज",
    SIGN_OUT: "साइन आउट",
    SIGN_IN: "दाखिल करना",
    SIGN_UP: "साइन अप करें",
    FULL_NAME: "पूरा नाम",
    EMAIL: "ईमेल",
    PASSWORD: "पासवर्ड",
    NEW_USER_PROMPT: "Netflix पर नए हैं? अभी साइन अप करें।",
    OLD_USER_PROMPT: "पहले से यूज़र हैं? अभी लॉग इन करें।",
    POPULAR_MOVIES: "लोकप्रिय",
    NOW_PLAYING: "अब खेल रहे हैं",
    TOP_RATED: "टॉप रेटेड",
    UPCOMING: "आगामी",
    HOME_PAGE:"मुख्य पृष्ठ"
  },
};

export default language;
